### PR TITLE
Girlcode page

### PR DESCRIPTION
**Pull request by afkatja**
Updated with the latest meetup

### CODE REVIEW

**Comment by Primigenus** [comment]
You're submitting a PR for develop but your merged from master. So you'll be missing more recent changes on develop. Can you merge those in and resubmit?

**Comment by afkatja** [comment]
@Primigenus Fixed. I was confused by the whole upstream thing.

**Comment by Primigenus** [comment]
@afkatja Please address the comments I left in February.

**Comment by afkatja** [comment]
- The images are now served from `{{assetUrl}}/images`
- vacancies link is absolute, to the Dutch site
- develop is merged in my branch
@Primigenus what else?

**Pull request merged**
