### PR TITLE
nicer #page box-shadow

### PR DESCRIPTION
**Pull request by sjoerdvisscher**

### CODE REVIEW

**Comment by sjoerdvisscher** [comment]
imho

**Comment by Primigenus** [comment]
The page has a box shadow for a reason (giving a visual distinction between the navigation and the main page on mobile). This isn't a bug that can be fixed just by removing the shadow, we should design a solution.

**Comment by Primigenus** [comment]
Fixed in https://github.com/Q42/q42.nl/commit/29c8dbf86454dd4893a8d182be801a00f92144b4

**Comment by sjoerdvisscher** [comment]
:+1:

**Pull request closed without merging**
